### ISSUE TITLE
【python 爬虫逆向 天安财险】填入jsonKey参数，url返回"statusMessage":"错误原因：渠道报文解析错误！"

### ISSUE THREAD

**Issue by WillpowerJin** [ChenZixinn/spider_reverse#2]
您好，我能通过AES加密的方式获取jsonKey的值，但是将jsonKey放入请求参数中则返回异常错误……

我的url请求参数填入格式如下，是哪里出了问题吗？
data = {
    "jsonKey": jsonKey
}

需要做什么特殊的处理吗？我也试了json.dumps(jsonKey, separators=(",", ":"))……但还是不行……

**Comment by ChenZixinn** [comment]
也可能是网站的加密方式改了，可以测试一下输入相同的参数得到是不是一样的密文

**Comment by WillpowerJin** [comment]
![image](https://github.com/ChenZixinn/spider_reverse/assets/62136069/cf7e2b85-424e-4089-93fb-f19549e7a2df)

请求头中有这两个加密参数，唉

**Comment by ChenZixinn** [comment]
那就是已经改版了噢，可以尝试逆向
