### ISSUE TITLE
巨量脚本提示 “not msToken” ，请问这个是失效了吗？

### ISSUE THREAD

**Issue by nicktzp** [ChenZixinn/spider_reverse#9]

**Comment by ChenZixinn** [comment]
失效了，当前的代码仅供参考。目前看到的msToken是通过window.localStorage里的xmst属性来设置的，可以hook一下，看看是如何生成的。
`
(function() {
    'use strict';

    // 保存原始的 localStorage.getItem 方法
    var originalGetItem = window.localStorage.getItem;

    // 重写 localStorage.getItem 方法以监听 'xmst' 键的变化
    window.localStorage.getItem = function(key) {
        if (key === 'xmst') {
            // 当 'xmst' 键被获取时，可以在这里添加你的监听逻辑
            console.log('localStorage 中的 "xmst" 键被获取');
            // 添加你的处理逻辑，例如触发事件或记录日志
        }
        return originalGetItem.apply(this, arguments);
    };

    // 保存原始的 localStorage.setItem 方法
    var originalSetItem = window.localStorage.setItem;

    // 重写 localStorage.setItem 方法以监听 'xmst' 键的变化
    window.localStorage.setItem = function(key, value) {
        if (key === 'xmst') {
            // 当 'xmst' 键被设置时，可以在这里添加你的监听逻辑
            console.log('localStorage 中的 "xmst" 键被设置为:', value);
            debugger;
            // 添加你的处理逻辑，例如触发事件或记录日志
        }
        return originalSetItem.apply(this, arguments);
    };
})();`
